# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipscout < Formula
  desc "A command line tool for network administrators and security analysts to quickly identify the origin and threat of an IP address.
"
  homepage "https://github.com/jonhadfield/ipscout"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jonhadfield/ipscout/releases/download/0.3.2/ipscout_darwin_amd64.tar.gz"
      sha256 "232f5742ac111345c9f002c3e42654b4c644a0567475166ae1dee62ad9fecbad"

      def install
        bin.install "ipscout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jonhadfield/ipscout/releases/download/0.3.2/ipscout_darwin_arm64.tar.gz"
      sha256 "42803c4815e7b4488f344dbdae33312646ce5417fe36aaf91ec44b537c26fc5f"

      def install
        bin.install "ipscout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jonhadfield/ipscout/releases/download/0.3.2/ipscout_linux_amd64.tar.gz"
      sha256 "41ef2c6e10526b43c67692f9c9e038c6ded11fe0a3673d70beb0a53ad1303e4e"
      def install
        bin.install "ipscout"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jonhadfield/ipscout/releases/download/0.3.2/ipscout_linux_arm64.tar.gz"
      sha256 "1e147faec1c1d470f7edc5cd81a28a66876111f22aeca5f1410bf29fe57dd919"
      def install
        bin.install "ipscout"
      end
    end
  end
end
