# This file was generated by GoReleaser. DO NOT EDIT.
cask "ipscout" do
  version "0.11.3"

  on_macos do
    on_arm do
      sha256 "ab15d79665f5aa6dee6308b8faa0e82a10d88a80e0d335fe8d5dafc78a239d35"
      url "https://github.com/jonhadfield/ipscout/releases/download/#{version}/ipscout_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1590387c491289b62040fbda8d50994c69bd55f412d9361c07e691478d3d359f"
      url "https://github.com/jonhadfield/ipscout/releases/download/#{version}/ipscout_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9b673d9d4de2e0161aee01bdcc0868a251bf7a8ff9d61949c5ffe1fcdd186244"
      url "https://github.com/jonhadfield/ipscout/releases/download/#{version}/ipscout_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "31838ab113e24e541302264d21f1278a38d0dd3bfbda31153703e7b624b5ce13"
      url "https://github.com/jonhadfield/ipscout/releases/download/#{version}/ipscout_linux_amd64.tar.gz"
    end
  end

  name "ipscout"
  desc "A command line tool for network administrators and security analysts to quickly identify the origin and threat of an IP address."
  homepage "https://github.com/jonhadfield/ipscout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ipscout"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ipscout"]
    end
  end

  # No zap stanza required
end
