# This file was generated by GoReleaser. DO NOT EDIT.
cask "ipscout" do
  version "0.6.3"

  on_macos do
    on_intel do
      sha256 "48a8644bdf3015242cfc035d32a298cde4ab515fce741290efb506acc6bbe904"
      url "https://github.com/jonhadfield/ipscout/releases/download/#{version}/ipscout_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bea05e378f971c87364a587f3e4c1273ec404d81c29a30c9529180b8c0d4ac78"
      url "https://github.com/jonhadfield/ipscout/releases/download/#{version}/ipscout_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ac20e28d8898658dd51ea9ea97be81d14d9192db7151704308e65ae06cf89989"
      url "https://github.com/jonhadfield/ipscout/releases/download/#{version}/ipscout_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c011ddcc3a3ab32cab6ca4adbca38cfea9360d511fab4d20629c8f0227d9949e"
      url "https://github.com/jonhadfield/ipscout/releases/download/#{version}/ipscout_linux_arm64.tar.gz"
    end
  end

  name "ipscout"
  desc "A command line tool for network administrators and security analysts to quickly identify the origin and threat of an IP address."
  homepage "https://github.com/jonhadfield/ipscout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ipscout"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ipscout"]
    end
  end

  # No zap stanza required

end
