# This file was generated by GoReleaser. DO NOT EDIT.
cask "ipscout" do
  version "0.12.4"

  on_macos do
    on_arm do
      sha256 "52ab09fd9061c57b6c2ee9b98723e08353fbc11af64b5adda93c58372440e310"
      url "https://github.com/jonhadfield/ipscout/releases/download/#{version}/ipscout_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f23ea5cf18939f5d5468e13d677eb4b223eea65ef16bfe9fb9b88555b168fe81"
      url "https://github.com/jonhadfield/ipscout/releases/download/#{version}/ipscout_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a657d92f332e60b12d5a9777e21cb54d3b541804184de7073a5615047efad923"
      url "https://github.com/jonhadfield/ipscout/releases/download/#{version}/ipscout_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d821e9d66611a56150d07081e9764e8721044c66b7212fcea4fae3e8533ab508"
      url "https://github.com/jonhadfield/ipscout/releases/download/#{version}/ipscout_linux_amd64.tar.gz"
    end
  end

  name "ipscout"
  desc "A command line tool for network administrators and security analysts to quickly identify the origin and threat of an IP address."
  homepage "https://github.com/jonhadfield/ipscout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ipscout"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ipscout"]
    end
  end

  # No zap stanza required
end
